### ISSUE TITLE
hello i need some help setting up your program

### ISSUE THREAD

**Issue by maroufim** [TheOfficialPeter/replit-desktop#1]
i have downloaded the zip file and i have both npm and nodejs installed all i need is instruction

**Comment by TheOfficialPeter** [comment]
Hello. Sorry for the late late reply. I forgot to mention that you need the electron package installed. Open your terminal in the root directory of the project and run the following command `npm i electron`. Then you can run the program using `npm start`

**Comment by TheOfficialPeter** [comment]
I updated the README. lemme know about any other issues with installation and Ill add the solutions to the README
